# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieKernel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieKernel
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'GoogleSignIn'
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'

  target 'MovieKernelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieKernelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
